name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity checks
        run: |
          python -m compileall -q app
          python -m pip check

      # необязательный дымовой тест: импорт и показ версий
      - name: Smoke import
        run: |
          python - << 'PY'
          import sys
          import importlib
          print("Python:", sys.version)
          for m in ("aiogram","aiohttp","jinja2","docx","reportlab"):
              mod = importlib.import_module(m)
              print(m, getattr(mod, "__version__", ""))
          print("OK")
          PY
